### ISSUE TITLE
[RFC] Runtime block options

### ISSUE THREAD

**Issue by artggd** [umanit/block-bundle#3]
It would be great to be able to pass an array of options while rendering a block w/ `umanit_block_render`.

**Comment by DjLeChuck** [comment]
Done for the v2, see 0a65cb6777a2f63401e4a31e44f384662cf3d99a

**Comment by artggd** [comment]
Well done dude, really cool seing this bundle maintained!

I agree with you on removing the phpdoc as it is useless most of the time now, maybe consider removing class docblocks too?

Appart from that, neat work! A few tests and you're good to go! :trollface: 
I'd be happy to help you out adding test coverage...
